### ISSUE TITLE
Trained models

### ISSUE THREAD

**Issue by IssamLaradji** [bcmi/F2GAN-Few-Shot-Image-Generation#10]
Thanks for the code! can we have access to the trained models please? Thank you :))

**Comment by hy-zpg** [comment]
Hi, the links to the trained model are updated.

**Comment by IssamLaradji** [comment]
I wasn't able to download it from Biadu, is it possible to have it in a different downlod link like Google drive or dropbox? Thanks!

**Comment by hy-zpg** [comment]
hi, I have uploaded the trained model to google drive https://drive.google.com/drive/folders/1_w6tdR9o85G2CDN6rzMCn9mrRD_RAgus?usp=sharing.

**Comment by IssamLaradji** [comment]
Thanks a lot! That's so helpful :))
