### ISSUE TITLE
About the split of classes

### ISSUE THREAD

**Issue by FriedRonaldo** [bcmi/F2GAN-Few-Shot-Image-Generation#16]
Hi, thanks for the interesting work! I hope to cite your work in my later research.

I have some questions about the source code and the paper.

1. In the paper, the split of the classes for train, test, validation for flower102 is the same as FUNIT's split. Then, the first 85 classes are for train and the remaining 17 classes are for the test. However, when I run "data_preparation.py" to prepare ".npy" file, the classes are not sorted so that class 087 is mapped to 0. It might not be the same as the split of FUNIT. Can you provide more details about it?

2. For EMNIST dataset, you mentioned that the split is: 28 (seen), 10 (unseen) among 48 classes.  And in "MatchingGAN" paper, the split is : (28, 10, 10) for 48 classes. However, EMNIST contains 47 classes (for "Balanced" split). Is it just a misspelling?

3. Some of the source codes for the test do not seem to be for F2GAN but MatchingGAN. As mentioned in #4 , there are some issues to run. Please provide some details to reproduce the results in the paper. 

Thanks.

**Comment by hy-zpg** [comment]
1. you can use the function 'generate_image_label_pairs' in data_preparation.py.
2. yes, in matchingGAN, we also randomly select 28 classes as training classes and select 10 classes as testing classes, the remaining data is selected as validation data.
3. the testing code data_with_matchingclassifier_for_quality_and_classifier.py is updated.
