### ISSUE TITLE
TypeError: cannot unpack non-iterable NoneType object

### ISSUE THREAD

**Issue by jinzhenmu** [bcmi/F2GAN-Few-Shot-Image-Generation#2]
> when i use " python3 train_dagan_with_matchingclassifier.py --dataset emnist --image_width 28 --batch_size 20  --experiment_title MMF2GAN/emnist1way3shot   --selected_classes 1 --support_number 3  --loss_G 1 --loss_D 1 --loss_CLA 1  --loss_recons_B 1 --loss_matching_G 0.01 --loss_matching_D 1 --loss_sim 1 "

- i got the wrong message at "dagan_networks_wgan_with_matchingclassifier.py", line 147, in generate ->      z_dim = self.z_dim)
TypeError: cannot unpack non-iterable NoneType object

> i can not to find what happen

**Comment by hy-zpg** [comment]
you can modify /utils/parser_utils.py by setting the default of '--matching ' as 1, or adding --matching 1 in the scripts.

**Comment by jinzhenmu** [comment]
- When I  modify /utils/parser_utils.py by setting the default of '--matching ' as 1

- the "TypeError: cannot unpack non-iterable NoneType object" is missing.

- but  i got a new error at "dagan_architectures_with_matchingclassifier.py", line 711, 

- in __call__   z_inputs_2_embedding, KL_loss_2 = self.VAE_kl_loss(conditional_input, 

- z_dim)

- TypeError: VAE_kl_loss() missing 3 required positional arguments: 'training', 

- 'dropout', and 'scope'

- And  what "dropout_rate " should i add?

**Comment by hy-zpg** [comment]
I have updated utils/parser_utils.py and dagan_architectures_with_matchingclassifier.py, you can download this two files and try again.
