### ISSUE TITLE
Question about the dataset setting

### ISSUE THREAD

**Issue by edward3862** [bcmi/F2GAN-Few-Shot-Image-Generation#6]
Hello, thanks for this repo.
The dataset split seems to differ from the description in the paper.

In the paper:
> For EMNIST, following MatchingGAN[16], we randomly select 28 categories from total 48 categories as training seen categories and select 10 categories from remaining categories as unseen testing categories

which suppose be 28:10:10 for train, val and test.

In the [code](https://github.com/bcmi/F2GAN-Few-Shot-Image-Generation/blob/0d26798c3a372bd4e15461f602da421ce9010034/data_with_matchingclassifier.py#L551):
> x_train, x_val, x_test = self.x[:35], self.x[35:42], self.x[42:]

which is 35:7:5 for train, val and test.

Which is the setting to re-implement the result in the paper?

**Comment by hy-zpg** [comment]
The setting of dataset split should be as described in the paper, and I have updated data_with_matchingclassifier.py.
